Booking/Controllers/BookingController.cs
using Booking.Data;
using Booking.Models;
using BusinessLogicLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using System.Text;

namespace Booking.Controllers
{
    public class BookingController : Controller
    {
        private readonly IBookingPlaceService _service;
        public BookingController(IBookingPlaceService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            IEnumerable<Booked> Data = _service.GetAll();
            return View(Data);

        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, ActionName("Create")]
        public IActionResult Created(Booked booked)
        {

            _service.Add(booked);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Booked data = _service.GetById(id);
            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(Booked booked)
        {
            _service.update(booked);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Booked data = _service.GetById(id);
            return View(data);

        }

        [HttpPost, ActionName("Delete")]
        public IActionResult Deleted(int id)
        {
            _service.Delete(id);
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            Booked data = _service.GetById(id);
            return View(data);
        }
    }
}

Booking/Controllers/CitiesController.cs
using Booking.Data;
using Booking.Models;
using BusinessLogicLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Booking.Controllers
{
    public class CitiesController : Controller
    {
        private readonly ICitiesService _service;

        public CitiesController(ICitiesService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            IEnumerable<Cities> data = _service.GetAll();
            return View(data);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var lstCountries = _service.GetAllCountries().Select(x => new SelectListItem
            {

                Text=x.CountryName,
                Value=x.Id.ToString()

            });

            ViewData["Countries"] = lstCountries;
            ViewData["City"] = new Cities();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Cities city)
        {
            try
            {
                _service.Add(city);
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Cities data = _service.GetById(id);
            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(Cities city)
        {
            _service.update(city);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            Cities data = _service.GetById(id);
            return View(data);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult Deleted(int id)
        {
            _service.Delete(id);
            return RedirectToAction("Index");
        }


        public IActionResult Details(int id)
        {
            Cities data = _service.GetById(id);
            return View(data);
        }
    }
}

Booking/Controllers/ReviewsController.cs
using BusinessLogicLayer;
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Booking.Controllers
{
   // [Authorize]
    public class ReviewsController : Controller
    {
        private readonly IReviewsService _service;
        public ReviewsController(IReviewsService service)
        {
            _service = service;
        }
        public IActionResult Index()
        {
           IEnumerable<Reviews> data = _service.GetAll();
            return View(data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Reviews reviews)
        {
            _service.Add(reviews);
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Reviews data = _service.GetById(id);
            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(Reviews reviews) 
        {
            _service.update(reviews);
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            Reviews data = _service.GetById(id);
            return View(data);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Reviews data = _service.GetById(id);
            return View(data);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult Deleted(int id)
        {
            _service.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Booking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Booking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Booking.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Booking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                      

                      

                        @if (User.IsInRole("Admin"))
                        {
                        

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Index">Booking</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Index">Cities</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Places" asp-action="Index">Places </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reviews" asp-action="Index">Reviews</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                            </li>

                         
                        }
                    </ul>
                    <ul class="navbar-nav mx-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        
                            <li class="nav-item ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        
                    }else {
                            <li class="nav-item ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                    
                    }
                    </ul>
                </div>
            </div>  
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Booking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

   @* <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @RenderSection("Scripts", required: false)*@
</body>
</html>